### ISSUE TITLE
regularized inversion

### ISSUE THREAD

**Issue by dinggeer** [polarch/Spherical-Array-Processing#5]
Hi, your code and paper have been very helpful to me. But I don't quite understand something, I hope you can help me answer it. 
I have a question about arraySHTfiltersTheory_radInverse.m.  in this script,  I think the variable 'beta' corresponds to the formula of λ in ref1, but why there is an extra SQRT, and according to the simulation results, it is correct to do so.  I hope you can help me solve my doubts, thank you very much!

**Comment by polarch** [comment]
Hi,

I think the formula in the original paper is wrong in that detail, and the sqrt() is needed there.
